//
// Created by tomas on 03.10.21.
//

#pragma once

//Ignore the fact that if you look at the autogenerated include/shader.vs and .fs files they are empty.
//They get filled up at compile time with data from vertex.shader and fragment.shader
class Shaders {
public:

    static const char *VertexSource() {
    //What in the name of auto-format is this
        return

#include <shaders/include/shader.vs>
                ;

    }

    static const char *FragmentSource() {
        return

#include <shaders/include/shader.fs>
                ;

    };

};