//
// Created by tomas on 03.10.21.
//

#pragma once

//Ignore the fact that if you look at the autogenerated include/shader.vs and .fs files they are empty.
//They get filled up at compile time with data from vertex.shader and fragment.shader
const char * VS =
#include <shaders/include/shader.vs>
;

const char * FS =
#include <shaders/include/shader.fs>
;

class Shaders {
public:
    static const char *VertexSource() {
        return VS;
    }
    static const char *FragmentSource() {
        return FS;
    };

};