//
// Created by tomas on 03.10.21.
//

#ifndef VUT_BP_SHADERS_H
#define VUT_BP_SHADERS_H

//Ignore the fact that if you look at the autogenerated include/shader.vs and .fs files they are empty.
//They get filled up at compile time with data from vertex.glsl and shader.glsl
const char* VertexSource =
#include "include/shader.vs"
;

const char *FragmentSource =
#include "include/shader.fs"
;

#endif //VUT_BP_SHADERS_H
